import json

t154_perfect_data = [
  {
    "id": "134583",
    "title": "Q1: Define a relation and a function",
    "question_text": "Define a relation and a function in mathematics. Explain the essential condition that distinguishes a function from a general relation.",
    "math_formula": "f: X \\to Y, \\quad (x, y_1) \\in f \\text{ and } (x, y_2) \\in f \\implies y_1 = y_2",
    "optA": "A function is a relation where every input x is mapped to exactly one unique output y",
    "optB": "A function allows one input x to map to multiple outputs y",
    "optC": "A relation requires numbers, whereas a function only allows variables",
    "optD": "A relation and a function are identical concepts with no difference",
    "correct_answer": "A function is a relation where every input x is mapped to exactly one unique output y",
    "show_image": 0,
    "image_url": None
  },
  {
    "id": "134584",
    "title": "Q2: Four representations of a relation",
    "question_text": "Explain the four different ways to represent a relation: ordered pairs, table of values, mapping diagram, and graph.",
    "math_formula": "\\text{Representations of Relations}",
    "optA": "Ordered pairs, Table of values, Mapping diagram, and Graph",
    "optB": "Input, Output, Domain, and Range",
    "optC": "Equation, Inequality, Matrix, and Vector",
    "optD": "Constant, Coefficient, Variable, and Exponent",
    "correct_answer": "Ordered pairs, Table of values, Mapping diagram, and Graph",
    "show_image": 1,
    "image_url": "/images/g9_t154_q2.png"
  },
  {
    "id": "134585",
    "title": "Q3: Determine if ordered pairs form a function",
    "question_text": "Determine whether the set of ordered pairs is a function: {(1, 3), (2, 5), (3, 7), (4, 9), (2, 8)}. Justify your answer.",
    "math_formula": "\\{(1, 3), (2, 5), (3, 7), (4, 9), (2, 8)\\}",
    "optA": "Is a function because all x-values are positive integers",
    "optB": "Not a function because input 2 maps to two different outputs (5 and 8)",
    "optC": "Is a function because all y-values are odd numbers",
    "optD": "Cannot be determined without graphing on a coordinate plane",
    "correct_answer": "Not a function because input 2 maps to two different outputs (5 and 8)",
    "show_image": 1,
    "image_url": "/images/g9_t154_q3.png"
  },
  {
    "id": "134586",
    "title": "Q4: Constant function ordered pairs",
    "question_text": "Determine whether the relation {(3, 4), (5, 4), (7, 4), (9, 4)} is a function. Explain why or why not.",
    "math_formula": "\\{(3, 4), (5, 4), (7, 4), (9, 4)\\}",
    "optA": "Is a function because each input x has exactly one output y (a constant function y = 4)",
    "optB": "Not a function because output 4 is repeated for multiple inputs",
    "optC": "Not a function because all y-values must be different",
    "optD": "Is a relation but neither a function nor a mapping",
    "correct_answer": "Is a function because each input x has exactly one output y (a constant function y = 4)",
    "show_image": 1,
    "image_url": "/images/g9_t154_q4.png"
  },
  {
    "id": "134587",
    "title": "Q5: Define domain and range of a relation",
    "question_text": "Define the domain and the range of a relation.",
    "math_formula": "\\text{Domain and Range Definitions}",
    "optA": "Domain is the set of all first coordinates (inputs x); Range is the set of all second coordinates (outputs y)",
    "optB": "Domain is the set of output values y; Range is the set of input values x",
    "optC": "Domain is the x-intercept; Range is the y-intercept of the line",
    "optD": "Domain refers to linear equations; Range refers to quadratic equations",
    "correct_answer": "Domain is the set of all first coordinates (inputs x); Range is the set of all second coordinates (outputs y)",
    "show_image": 1,
    "image_url": "/images/g9_t154_q5.png"
  },
  {
    "id": "134588",
    "title": "Q6: Find domain and range from ordered pairs",
    "question_text": "Find the domain and range of the relation: {(-3, 2), (-1, 5), (0, -4), (2, 7), (4, 1)}.",
    "math_formula": "\\{(-3, 2), (-1, 5), (0, -4), (2, 7), (4, 1)\\}",
    "optA": "Domain = {-3, -1, 0, 2, 4}, Range = {-4, 1, 2, 5, 7}",
    "optB": "Domain = {-4, 1, 2, 5, 7}, Range = {-3, -1, 0, 2, 4}",
    "optC": "Domain = {-3, -1, 0}, Range = {2, 5, -4, 7, 1}",
    "optD": "Domain = all real numbers, Range = all real numbers",
    "correct_answer": "Domain = {-3, -1, 0, 2, 4}, Range = {-4, 1, 2, 5, 7}",
    "show_image": 1,
    "image_url": "/images/g9_t154_q6.png"
  },
  {
    "id": "134589",
    "title": "Q7: Vertical Line Test definition",
    "question_text": "State the Vertical Line Test and explain how it determines whether a given curve on the Cartesian plane represents a function.",
    "math_formula": "\\text{Vertical Line Test}",
    "optA": "A graph represents a function if and only if no vertical line intersects the curve at more than one point",
    "optB": "A graph represents a function if any horizontal line crosses it at exactly one point",
    "optC": "A graph is a function if a vertical line intersects it at at least two points",
    "optD": "The test determines whether a linear graph has a positive or negative slope",
    "correct_answer": "A graph represents a function if and only if no vertical line intersects the curve at more than one point",
    "show_image": 1,
    "image_url": "/images/g9_t154_q7.png"
  },
  {
    "id": "134590",
    "title": "Q8: Vertical Line Test on circle",
    "question_text": "Apply the vertical line test to explain whether a circle x² + y² = 25 is a function.",
    "math_formula": "x^2 + y^2 = 25",
    "optA": "Is a function because a circle is a symmetric geometric figure",
    "optB": "Not a function because a vertical line x = c (-5 < c < 5) intersects the circle at two points",
    "optC": "Is a function because every x-value corresponds to a positive y-value",
    "optD": "Not a relation because it cannot be written as ordered pairs",
    "correct_answer": "Not a function because a vertical line x = c (-5 < c < 5) intersects the circle at two points",
    "show_image": 1,
    "image_url": "/images/g9_t154_q8.png"
  },
  {
    "id": "134591",
    "title": "Q9: Function domain and range for y = 2x - 5",
    "question_text": "Determine if the relation represented by the equation y = 2x - 5 is a function and specify its domain and range in interval notation.",
    "math_formula": "y = 2x - 5",
    "optA": "Is a function; Domain = (-∞, ∞), Range = (-∞, ∞)",
    "optB": "Not a function; Domain = [0, ∞), Range = (-∞, ∞)",
    "optC": "Is a function; Domain = [5, ∞), Range = [-5, ∞)",
    "optD": "Not a function; Domain = (-∞, 5], Range = (-∞, 0]",
    "correct_answer": "Is a function; Domain = (-∞, ∞), Range = (-∞, ∞)",
    "show_image": 1,
    "image_url": "/images/g9_t154_q9.png"
  },
  {
    "id": "134592",
    "title": "Q10: Domain and range of square root function",
    "question_text": "Determine the domain and range of the function f(x) = √(x - 3).",
    "math_formula": "f(x) = \\sqrt{x - 3}",
    "optA": "Domain = [3, ∞), Range = [0, ∞)",
    "optB": "Domain = (-∞, 3], Range = (-∞, 0]",
    "optC": "Domain = (3, ∞), Range = (0, ∞)",
    "optD": "Domain = (-∞, ∞), Range = [3, ∞)",
    "correct_answer": "Domain = [3, ∞), Range = [0, ∞)",
    "show_image": 1,
    "image_url": "/images/g9_t154_q10.png"
  },
  {
    "id": "134593",
    "title": "Q11: Domain of rational function",
    "question_text": "Determine the domain of the rational function f(x) = (2x + 1) / (x² - 9).",
    "math_formula": "f(x) = \\frac{2x + 1}{x^2 - 9}",
    "optA": "Domain = {x ∈ ℝ | x ≠ -3 and x ≠ 3}",
    "optB": "Domain = {x ∈ ℝ | x ≠ -1/2}",
    "optC": "Domain = {x ∈ ℝ | x > 9}",
    "optD": "Domain = all real numbers ℝ",
    "correct_answer": "Domain = {x ∈ ℝ | x ≠ -3 and x ≠ 3}",
    "show_image": 0,
    "image_url": None
  },
  {
    "id": "134594",
    "title": "Q12: Evaluate quadratic function",
    "question_text": "Evaluate the function f(x) = 3x² - 5x + 2 at: a) f(0), b) f(-2), c) f(4).",
    "math_formula": "f(x) = 3x^2 - 5x + 2",
    "optA": "f(0) = 2, f(-2) = 24, f(4) = 30",
    "optB": "f(0) = 0, f(-2) = 16, f(4) = 28",
    "optC": "f(0) = 2, f(-2) = 4, f(4) = 34",
    "optD": "f(0) = -5, f(-2) = 24, f(4) = 30",
    "correct_answer": "f(0) = 2, f(-2) = 24, f(4) = 30",
    "show_image": 0,
    "image_url": None
  },
  {
    "id": "134595",
    "title": "Q13: Find input x given f(x)",
    "question_text": "Given f(x) = 4x - 7, find the value of x for which f(x) = 25.",
    "math_formula": "f(x) = 4x - 7 = 25",
    "optA": "x = 8",
    "optB": "x = 4.5",
    "optC": "x = 93",
    "optD": "x = 7",
    "correct_answer": "x = 8",
    "show_image": 0,
    "image_url": None
  },
  {
    "id": "134596",
    "title": "Q14: Evaluate function with algebraic expression",
    "question_text": "Given g(x) = x² + 3x, find and simplify the expression for g(a + 2).",
    "math_formula": "g(a + 2) = (a + 2)^2 + 3(a + 2)",
    "optA": "g(a + 2) = a² + 7a + 10",
    "optB": "g(a + 2) = a² + 3a + 2",
    "optC": "g(a + 2) = a² + 5a + 6",
    "optD": "g(a + 2) = a² + 7a + 4",
    "correct_answer": "g(a + 2) = a² + 7a + 10",
    "show_image": 0,
    "image_url": None
  },
  {
    "id": "134597",
    "title": "Q15: Difference quotient calculation",
    "question_text": "Given h(t) = 16t² - 4t, evaluate and simplify the difference quotient: [h(t + Δt) - h(t)] / Δt.",
    "math_formula": "\\frac{h(t + \\Delta t) - h(t)}{\\Delta t}",
    "optA": "32t + 16Δt - 4",
    "optB": "16t + 32Δt - 4",
    "optC": "32t - 4",
    "optD": "16t² + 16Δt - 4",
    "correct_answer": "32t + 16Δt - 4",
    "show_image": 0,
    "image_url": None
  },
  {
    "id": "134598",
    "title": "Q16: Cell phone postpaid plan function",
    "question_text": "A cell phone postpaid plan charges a fixed monthly service fee of ₱499 plus ₱6.50 per excess minute of calls. Write a function C(m) representing the monthly bill for m excess minutes.",
    "math_formula": "C(m) = 499 + 6.50m",
    "optA": "C(m) = 499 + 6.50m",
    "optB": "C(m) = 6.50 + 499m",
    "optC": "C(m) = 499m - 6.50",
    "optD": "C(m) = (499 + 6.50)m",
    "correct_answer": "C(m) = 499 + 6.50m",
    "show_image": 0,
    "image_url": None
  },
  {
    "id": "134599",
    "title": "Q17: Evaluate cell phone bill function",
    "question_text": "Using the function C(m) = 499 + 6.50m, calculate the bill for 45 excess minutes, and determine how many excess minutes were used if the bill was ₱921.50.",
    "math_formula": "C(45) = 499 + 6.50(45), \\quad 921.50 = 499 + 6.50m",
    "optA": "C(45) = ₱791.50, and 65 excess minutes were used for a bill of ₱921.50",
    "optB": "C(45) = ₱780.00, and 70 excess minutes were used for a bill of ₱921.50",
    "optC": "C(45) = ₱820.50, and 60 excess minutes were used for a bill of ₱921.50",
    "optD": "C(45) = ₱741.50, and 50 excess minutes were used for a bill of ₱921.50",
    "correct_answer": "C(45) = ₱791.50, and 65 excess minutes were used for a bill of ₱921.50",
    "show_image": 0,
    "image_url": None
  },
  {
    "id": "134600",
    "title": "Q18: Tricycle fare step function",
    "question_text": "A tricycle ride costs ₱15 for the first kilometer and ₱3 for each additional kilometer or fraction thereof. Write a function to model the fare F(d) for distance d.",
    "math_formula": "F(d) = 15 + 3\\lceil d - 1 \\rceil \\quad \\text{for } d > 1",
    "optA": "F(d) = 15 for 0 < d ≤ 1, and F(d) = 15 + 3⌈d - 1⌉ for d > 1",
    "optB": "F(d) = 18d for all d > 0",
    "optC": "F(d) = 15d + 3 for all d > 0",
    "optD": "F(d) = 3 + 15d for d > 1",
    "correct_answer": "F(d) = 15 for 0 < d ≤ 1, and F(d) = 15 + 3⌈d - 1⌉ for d > 1",
    "show_image": 1,
    "image_url": "/images/g9_t154_q18.png"
  },
  {
    "id": "134601",
    "title": "Q19: Identify mapping diagram correspondence",
    "question_text": "Identify whether the mapping diagram represents a one-to-one, many-to-one, or one-to-many correspondence, and state whether it is a function.",
    "math_formula": "\\text{Mapping Correspondence Classification}",
    "optA": "One-to-one correspondence, which IS a function",
    "optB": "One-to-many correspondence, which IS NOT a function",
    "optC": "Many-to-one correspondence, which IS NOT a function",
    "optD": "Many-to-many correspondence, which IS a function",
    "correct_answer": "One-to-one correspondence, which IS a function",
    "show_image": 1,
    "image_url": "/images/g9_t154_q19.png"
  },
  {
    "id": "134602",
    "title": "Q20: Why one-to-many is not a function",
    "question_text": "Explain why a one-to-many correspondence can never be a function.",
    "math_formula": "\\text{One-to-Many Non-Function Criterion}",
    "optA": "Because a single input x is paired with more than one output y, violating the definition of a function",
    "optB": "Because multiple inputs map to a single output y",
    "optC": "Because domain values cannot be negative numbers",
    "optD": "Because it creates a horizontal line on a graph",
    "correct_answer": "Because a single input x is paired with more than one output y, violating the definition of a function",
    "show_image": 1,
    "image_url": "/images/g9_t154_q20.png"
  },
  {
    "id": "134603",
    "title": "Q21: Range for discrete domain",
    "question_text": "Find the range of the function f(x) = x² - 4 for the discrete domain D = {-3, -1, 0, 2, 5}.",
    "math_formula": "f(x) = x^2 - 4, \\quad D = \\{-3, -1, 0, 2, 5\\}",
    "optA": "Range = {-4, -3, 0, 5, 21}",
    "optB": "Range = {-3, -1, 0, 2, 5}",
    "optC": "Range = {5, -3, -4, 0, 25}",
    "optD": "Range = {0, 4, 9, 16, 25}",
    "correct_answer": "Range = {-4, -3, 0, 5, 21}",
    "show_image": 1,
    "image_url": "/images/g9_t154_q21.png"
  },
  {
    "id": "134604",
    "title": "Q22: Domain and range of linear function",
    "question_text": "Find the domain and range of the linear function f(x) = -3x + 8.",
    "math_formula": "f(x) = -3x + 8",
    "optA": "Domain = (-∞, ∞), Range = (-∞, ∞)",
    "optB": "Domain = [0, ∞), Range = (-∞, 8]",
    "optC": "Domain = (-∞, 8], Range = [0, ∞)",
    "optD": "Domain = {x | x ≠ 8/3}, Range = {y | y ≠ 8}",
    "correct_answer": "Domain = (-∞, ∞), Range = (-∞, ∞)",
    "show_image": 0,
    "image_url": None
  },
  {
    "id": "134605",
    "title": "Q23: Domain and range of line segment graph",
    "question_text": "Determine the domain and range of the function graphed as a line segment with endpoints at (-4, -2) and (6, 5).",
    "math_formula": "\\text{Line Segment from } (-4, -2) \\text{ to } (6, 5)",
    "optA": "Domain = [-4, 6], Range = [-2, 5]",
    "optB": "Domain = [-2, 5], Range = [-4, 6]",
    "optC": "Domain = (-4, 6), Range = (-2, 5)",
    "optD": "Domain = [-4, 5], Range = [-2, 6]",
    "correct_answer": "Domain = [-4, 6], Range = [-2, 5]",
    "show_image": 1,
    "image_url": "/images/g9_t154_q23.png"
  },
  {
    "id": "134606",
    "title": "Q24: Domain and range of absolute value function",
    "question_text": "Find the domain and range of the function f(x) = |x - 2| + 3.",
    "math_formula": "f(x) = |x - 2| + 3",
    "optA": "Domain = (-∞, ∞), Range = [3, ∞)",
    "optB": "Domain = [2, ∞), Range = [3, ∞)",
    "optC": "Domain = (-∞, ∞), Range = (-∞, 3]",
    "optD": "Domain = [3, ∞), Range = [2, ∞)",
    "correct_answer": "Domain = (-∞, ∞), Range = [3, ∞)",
    "show_image": 1,
    "image_url": "/images/g9_t154_q24.png"
  },
  {
    "id": "134607",
    "title": "Q25: Bakery custom cake cost function",
    "question_text": "A bakery sells custom cakes for ₱350 each plus a flat delivery charge of ₱80 per order. Express total cost C as a function of the number of cakes n, and state the practical domain.",
    "math_formula": "C(n) = 350n + 80",
    "optA": "C(n) = 350n + 80; Domain: n ∈ {0, 1, 2, 3, ...} (non-negative integers)",
    "optB": "C(n) = 80n + 350; Domain: all real numbers ℝ",
    "optC": "C(n) = 350 + 80n; Domain: n ≥ 80",
    "optD": "C(n) = (350 + 80)n; Domain: n > 0",
    "correct_answer": "C(n) = 350n + 80; Domain: n ∈ {0, 1, 2, 3, ...} (non-negative integers)",
    "show_image": 0,
    "image_url": None
  },
  {
    "id": "134608",
    "title": "Q26: Sideways parabola relation x = y²",
    "question_text": "Determine whether the equation x = y² represents y as a function of x. Explain your reasoning.",
    "math_formula": "x = y^2",
    "optA": "No, because for x > 0, y = ±√x (a single x maps to two y-values)",
    "optB": "Yes, because every real number x has a square root",
    "optC": "Yes, because x = y² is a horizontal line",
    "optD": "No, because x cannot take negative values",
    "correct_answer": "No, because for x > 0, y = ±√x (a single x maps to two y-values)",
    "show_image": 1,
    "image_url": "/images/g9_t154_q26.png"
  },
  {
    "id": "134609",
    "title": "Q27: Function evaluation and composition",
    "question_text": "Given f(x) = 2x + 3 and g(x) = x² - 1, find: a) f(3) + g(3), b) f(g(2)).",
    "math_formula": "f(x) = 2x + 3, \\quad g(x) = x^2 - 1",
    "optA": "a) f(3) + g(3) = 17, b) f(g(2)) = 9",
    "optB": "a) f(3) + g(3) = 15, b) f(g(2)) = 11",
    "optC": "a) f(3) + g(3) = 18, b) f(g(2)) = 7",
    "optD": "a) f(3) + g(3) = 14, b) f(g(2)) = 13",
    "correct_answer": "a) f(3) + g(3) = 17, b) f(g(2)) = 9",
    "show_image": 0,
    "image_url": None
  },
  {
    "id": "134610",
    "title": "Q28: Water tank draining function",
    "question_text": "A water tank contains 1,200 liters of water and drains at a constant rate of 25 liters per minute. Write a linear function V(t) for remaining volume after t minutes and determine the practical domain and range.",
    "math_formula": "V(t) = 1200 - 25t",
    "optA": "V(t) = 1200 - 25t; Domain: [0, 48] minutes; Range: [0, 1200] liters",
    "optB": "V(t) = 25t - 1200; Domain: [0, 25] minutes; Range: [0, 48] liters",
    "optC": "V(t) = 1200 + 25t; Domain: (-∞, ∞); Range: (-∞, ∞)",
    "optD": "V(t) = 1200 - 25t; Domain: [0, 1200]; Range: [0, 48]",
    "correct_answer": "V(t) = 1200 - 25t; Domain: [0, 48] minutes; Range: [0, 1200] liters",
    "show_image": 1,
    "image_url": "/images/g9_t154_q28.png"
  },
  {
    "id": "134611",
    "title": "Q29: Real-world function identification",
    "question_text": "Identify which of the following real-world relationships represents a function: a) Student ID number to student name; b) Person's age to shoe size; c) Country to capital city.",
    "math_formula": "\\text{Real-World Function Criteria}",
    "optA": "a) and c) are functions; b) is not a function",
    "optB": "Only a) is a function; b) and c) are not",
    "optC": "All three a), b), and c) are functions",
    "optD": "None of the relationships represent a function",
    "correct_answer": "a) and c) are functions; b) is not a function",
    "show_image": 0,
    "image_url": None
  },
  {
    "id": "134612",
    "title": "Q30: Piecewise function evaluation",
    "question_text": "Given the piecewise function: f(x) = 2x + 1 for x < 0, and f(x) = x² - 3 for x ≥ 0. Evaluate f(-3), f(0), and f(4).",
    "math_formula": "f(x) = \\begin{cases} 2x + 1 & \\text{if } x < 0 \\\\ x^2 - 3 & \\text{if } x \\ge 0 \\end{cases}",
    "optA": "f(-3) = -5, f(0) = -3, f(4) = 13",
    "optB": "f(-3) = 6, f(0) = 1, f(4) = 9",
    "optC": "f(-3) = -5, f(0) = 1, f(4) = 13",
    "optD": "f(-3) = -3, f(0) = 0, f(4) = 16",
    "correct_answer": "f(-3) = -5, f(0) = -3, f(4) = 13",
    "show_image": 0,
    "image_url": None
  },
  {
    "id": "134613",
    "title": "Q31: Parking fee piecewise function",
    "question_text": "Write a piecewise function representing parking fees: ₱30 for the first 2 hours, and ₱15 for each additional hour or fraction thereof.",
    "math_formula": "P(t) = \\begin{cases} 30 & \\text{if } 0 < t \\le 2 \\\\ 30 + 15\\lceil t - 2 \\rceil & \\text{if } t > 2 \\end{cases}",
    "optA": "P(t) = 30 for 0 < t ≤ 2, and P(t) = 30 + 15⌈t - 2⌉ for t > 2",
    "optB": "P(t) = 45t for all t > 0",
    "optC": "P(t) = 15t + 30 for all t > 0",
    "optD": "P(t) = 30t - 15 for t > 2",
    "correct_answer": "P(t) = 30 for 0 < t ≤ 2, and P(t) = 30 + 15⌈t - 2⌉ for t > 2",
    "show_image": 1,
    "image_url": "/images/g9_t154_q31.png"
  },
  {
    "id": "134614",
    "title": "Q32: Table of values linear test",
    "question_text": "Determine whether the table of values represents a linear function by testing for constant first differences: x = [1, 2, 3, 4, 5], y = [7, 11, 15, 19, 23].",
    "math_formula": "\\Delta y = 11 - 7 = 15 - 11 = 19 - 15 = 23 - 19 = 4",
    "optA": "Yes, it is linear with a constant first difference of 4 (rule y = 4x + 3)",
    "optB": "No, it is quadratic because the values are increasing rapidly",
    "optC": "Yes, it is linear with a constant slope of 7",
    "optD": "No, because x does not start at 0",
    "correct_answer": "Yes, it is linear with a constant first difference of 4 (rule y = 4x + 3)",
    "show_image": 1,
    "image_url": "/images/g9_t154_q32.png"
  },
  {
    "id": "134615",
    "title": "Q33: Zeros of linear function",
    "question_text": "Find the zeros of the function f(x) = 5x - 35.",
    "math_formula": "5x - 35 = 0 \\implies x = 7",
    "optA": "x = 7",
    "optB": "x = -7",
    "optC": "x = 35",
    "optD": "x = 5",
    "correct_answer": "x = 7",
    "show_image": 1,
    "image_url": "/images/g9_t154_q33.png"
  },
  {
    "id": "134616",
    "title": "Q34: Zeros of quadratic function",
    "question_text": "Find the zeros of the function g(x) = x² - 7x + 12.",
    "math_formula": "x^2 - 7x + 12 = 0 \\implies (x - 3)(x - 4) = 0",
    "optA": "x = 3 and x = 4",
    "optB": "x = -3 and x = -4",
    "optC": "x = 1 and x = 12",
    "optD": "x = 7 and x = 12",
    "correct_answer": "x = 3 and x = 4",
    "show_image": 1,
    "image_url": "/images/g9_t154_q34.png"
  },
  {
    "id": "134617",
    "title": "Q35: Independent vs dependent variable concept",
    "question_text": "Explain the concept of independent variable and dependent variable in a function.",
    "math_formula": "y = f(x)",
    "optA": "Independent variable (input x) can be changed freely; Dependent variable (output y) changes in response to x",
    "optB": "Independent variable is output y; Dependent variable is input x",
    "optC": "Both variables must always be positive numbers",
    "optD": "Independent variable represents time only; Dependent variable represents distance only",
    "correct_answer": "Independent variable (input x) can be changed freely; Dependent variable (output y) changes in response to x",
    "show_image": 1,
    "image_url": "/images/g9_t154_q35.png"
  },
  {
    "id": "134618",
    "title": "Q36: Bean plant growth slope and y-intercept",
    "question_text": "In a science experiment, the height h (in cm) of a growing bean plant after d days is given by h(d) = 1.5d + 2. Interpret the meaning of the slope 1.5 and the y-intercept 2 in context.",
    "math_formula": "h(d) = 1.5d + 2",
    "optA": "Slope 1.5 is the growth rate of 1.5 cm/day; y-intercept 2 is the initial height of 2 cm at day 0",
    "optB": "Slope 2 is the growth rate; y-intercept 1.5 is the maximum height",
    "optC": "Slope 1.5 is the number of days; y-intercept 2 is the total cost",
    "optD": "Slope 2 is the initial height; y-intercept 1.5 is the height after 1 week",
    "correct_answer": "Slope 1.5 is the growth rate of 1.5 cm/day; y-intercept 2 is the initial height of 2 cm at day 0",
    "show_image": 1,
    "image_url": "/images/g9_t154_q36.png"
  },
  {
    "id": "134619",
    "title": "Q37: Domain of square root in denominator",
    "question_text": "State the domain of the function f(x) = 1 / √(2x - 8).",
    "math_formula": "f(x) = \\frac{1}{\\sqrt{2x - 8}} \\implies 2x - 8 > 0",
    "optA": "Domain = (4, ∞) or {x ∈ ℝ | x > 4}",
    "optB": "Domain = [4, ∞) or {x ∈ ℝ | x ≥ 4}",
    "optC": "Domain = (-∞, 4) or {x ∈ ℝ | x < 4}",
    "optD": "Domain = {x ∈ ℝ | x ≠ 4}",
    "correct_answer": "Domain = (4, ∞) or {x ∈ ℝ | x > 4}",
    "show_image": 0,
    "image_url": None
  },
  {
    "id": "134620",
    "title": "Q38: Graph linear function f(x) = -2x + 4",
    "question_text": "Graph the function f(x) = -2x + 4 on the coordinate plane and identify its domain and range.",
    "math_formula": "f(x) = -2x + 4",
    "optA": "Domain = (-∞, ∞), Range = (-∞, ∞); Line passes through (0, 4) and (2, 0)",
    "optB": "Domain = [0, ∞), Range = (-∞, 4]; Line passes through (0, 0) and (2, 4)",
    "optC": "Domain = (-∞, 4], Range = [0, ∞); Line passes through (4, 0) and (0, 2)",
    "optD": "Domain = [-2, 4], Range = [-2, 4]; Line passes through (0, -2) and (4, 0)",
    "correct_answer": "Domain = (-∞, ∞), Range = (-∞, ∞); Line passes through (0, 4) and (2, 0)",
    "show_image": 1,
    "image_url": "/images/g9_t154_q38.png"
  },
  {
    "id": "134621",
    "title": "Q39: Determine x- and y-intercepts",
    "question_text": "Determine the x- and y-intercepts of the function f(x) = (3/4)x - 6.",
    "math_formula": "f(x) = \\frac{3}{4}x - 6",
    "optA": "x-intercept = (8, 0), y-intercept = (0, -6)",
    "optB": "x-intercept = (-6, 0), y-intercept = (0, 8)",
    "optC": "x-intercept = (6, 0), y-intercept = (0, -8)",
    "optD": "x-intercept = (4/3, 0), y-intercept = (0, 6)",
    "correct_answer": "x-intercept = (8, 0), y-intercept = (0, -6)",
    "show_image": 1,
    "image_url": "/images/g9_t154_q39.png"
  },
  {
    "id": "134622",
    "title": "Q40: Printing company cost function",
    "question_text": "A printing company charges ₱2.50 per page for the first 100 pages, and ₱1.80 per page for orders above 100 pages. Write a piecewise function for total cost P(n).",
    "math_formula": "P(n) = \\begin{cases} 2.50n & \\text{if } 0 \\le n \\le 100 \\\\ 250 + 1.80(n - 100) & \\text{if } n > 100 \\end{cases}",
    "optA": "P(n) = 2.50n for 0 ≤ n ≤ 100, and P(n) = 250 + 1.80(n - 100) for n > 100",
    "optB": "P(n) = 1.80n for all n",
    "optC": "P(n) = 4.30n - 100 for n > 100",
    "optD": "P(n) = 2.50n + 1.80 for n > 0",
    "correct_answer": "P(n) = 2.50n for 0 ≤ n ≤ 100, and P(n) = 250 + 1.80(n - 100) for n > 100",
    "show_image": 1,
    "image_url": "/images/g9_t154_q40.png"
  },
  {
    "id": "134623",
    "title": "Q41: Linear function rule from two points",
    "question_text": "If f(x) = ax + b where f(2) = 7 and f(-1) = -2, find the constants a and b and write the function rule.",
    "math_formula": "f(2) = 2a + b = 7, \\quad f(-1) = -a + b = -2",
    "optA": "a = 3, b = 1; Rule: f(x) = 3x + 1",
    "optB": "a = 2, b = 3; Rule: f(x) = 2x + 3",
    "optC": "a = 4, b = -1; Rule: f(x) = 4x - 1",
    "optD": "a = 1, b = 5; Rule: f(x) = x + 5",
    "correct_answer": "a = 3, b = 1; Rule: f(x) = 3x + 1",
    "show_image": 0,
    "image_url": None
  },
  {
    "id": "134624",
    "title": "Q42: Semi-circle function domain and range",
    "question_text": "Determine whether the relation defined by {(x, y) | y = √(25 - x²)} is a function and determine its domain and range.",
    "math_formula": "y = \\sqrt{25 - x^2}",
    "optA": "Is a function; Domain = [-5, 5], Range = [0, 5]",
    "optB": "Not a function; Domain = (-∞, ∞), Range = [-5, 5]",
    "optC": "Is a function; Domain = [0, 5], Range = [-5, 5]",
    "optD": "Not a function; Domain = [-25, 25], Range = [0, 25]",
    "correct_answer": "Is a function; Domain = [-5, 5], Range = [0, 5]",
    "show_image": 1,
    "image_url": "/images/g9_t154_q42.png"
  },
  {
    "id": "134625",
    "title": "Q43: Vertical line x = c relation vs function",
    "question_text": "Explain why the graph of a vertical line x = c is a relation but not a function.",
    "math_formula": "x = c",
    "optA": "Not a function because a single input x = c maps to infinitely many y-values",
    "optB": "Is a function because it is a straight line",
    "optC": "Not a function because it has a slope of zero",
    "optD": "Is a function because it passes the horizontal line test",
    "correct_answer": "Not a function because a single input x = c maps to infinitely many y-values",
    "show_image": 1,
    "image_url": "/images/g9_t154_q43.png"
  },
  {
    "id": "134626",
    "title": "Q44: Horizontal line y = k function properties",
    "question_text": "Explain why the graph of a horizontal line y = k is a function and state its domain and range.",
    "math_formula": "y = k",
    "optA": "Is a function because every input x maps to the single output k; Domain = (-∞, ∞), Range = {k}",
    "optB": "Not a function because y is constant and does not change",
    "optC": "Is a function; Domain = {k}, Range = (-∞, ∞)",
    "optD": "Not a function because it fails the vertical line test",
    "correct_answer": "Is a function because every input x maps to the single output k; Domain = (-∞, ∞), Range = {k}",
    "show_image": 1,
    "image_url": "/images/g9_t154_q44.png"
  },
  {
    "id": "134627",
    "title": "Q45: Rational function solving for x",
    "question_text": "Given f(x) = (x + 2) / (x - 5), find the value of x such that f(x) = 3.",
    "math_formula": "\\frac{x + 2}{x - 5} = 3 \\implies x + 2 = 3(x - 5)",
    "optA": "x = 8.5 (or 17/2)",
    "optB": "x = 5.5",
    "optC": "x = -6.5",
    "optD": "x = 11",
    "correct_answer": "x = 8.5 (or 17/2)",
    "show_image": 0,
    "image_url": None
  },
  {
    "id": "134628",
    "title": "Q46: Greatest integer step function domain and range",
    "question_text": "Find the domain and range of the function shown by a step function (greatest integer function) f(x) = ⌊x⌋.",
    "math_formula": "f(x) = \\lfloor x \\rfloor",
    "optA": "Domain = all real numbers ℝ, Range = set of all integers ℤ",
    "optB": "Domain = set of all integers ℤ, Range = all real numbers ℝ",
    "optC": "Domain = [0, ∞), Range = [0, ∞)",
    "optD": "Domain = all real numbers ℝ, Range = all real numbers ℝ",
    "correct_answer": "Domain = all real numbers ℝ, Range = set of all integers ℤ",
    "show_image": 1,
    "image_url": "/images/g9_t154_q46.png"
  },
  {
    "id": "134629",
    "title": "Q47: Overtime pay function W(h)",
    "question_text": "A worker earns ₱75 per hour for regular 40-hour workweeks, and ₱112.50 per hour for overtime hours. Express weekly pay W as a function of total hours h worked.",
    "math_formula": "W(h) = \\begin{cases} 75h & \\text{if } 0 \\le h \\le 40 \\\\ 3000 + 112.50(h - 40) & \\text{if } h > 40 \\end{cases}",
    "optA": "W(h) = 75h for 0 ≤ h ≤ 40, and W(h) = 3000 + 112.50(h - 40) for h > 40",
    "optB": "W(h) = 112.50h for all h > 0",
    "optC": "W(h) = 75h + 112.50 for all h",
    "optD": "W(h) = 3000h - 40 for h > 40",
    "correct_answer": "W(h) = 75h for 0 ≤ h ≤ 40, and W(h) = 3000 + 112.50(h - 40) for h > 40",
    "show_image": 1,
    "image_url": "/images/g9_t154_q47.png"
  },
  {
    "id": "134630",
    "title": "Q48: Biological mother relation",
    "question_text": "Determine if the relation { (a, b) : a is the biological mother of b } is a function from the set of all mothers to all children, or vice versa.",
    "math_formula": "\\text{Mother to Child vs Child to Mother Relation}",
    "optA": "Not a function from mothers to children; IS a function from children to mothers",
    "optB": "IS a function from mothers to children; Not a function from children to mothers",
    "optC": "IS a function in both directions",
    "optD": "Is neither a relation nor a function in either direction",
    "correct_answer": "Not a function from mothers to children; IS a function from children to mothers",
    "show_image": 0,
    "image_url": None
  },
  {
    "id": "134631",
    "title": "Q49: Symmetry test even or odd function",
    "question_text": "If f(x) = 2x³ - 3x² + 4x - 5, determine whether f(x) is an even function, odd function, or neither by testing f(-x).",
    "math_formula": "f(-x) = -2x^3 - 3x^2 - 4x - 5",
    "optA": "Neither even nor odd",
    "optB": "Even function",
    "optC": "Odd function",
    "optD": "Both even and odd function",
    "correct_answer": "Neither even nor odd",
    "show_image": 0,
    "image_url": None
  },
  {
    "id": "134632",
    "title": "Q50: Quadratic function domain and range",
    "question_text": "State the domain and range of the function f(x) = -x² + 6x - 5.",
    "math_formula": "f(x) = -(x - 3)^2 + 4",
    "optA": "Domain = (-∞, ∞), Range = (-∞, 4]",
    "optB": "Domain = (-∞, ∞), Range = [4, ∞)",
    "optC": "Domain = [1, 5], Range = [0, 4]",
    "optD": "Domain = (-∞, 3], Range = (-∞, 0]",
    "correct_answer": "Domain = (-∞, ∞), Range = (-∞, 4]",
    "show_image": 1,
    "image_url": "/images/g9_t154_q50.png"
  }
]

with open('scratch/t154_50_built_questions.json', 'w', encoding='utf-8') as f:
    json.dump(t154_perfect_data, f, indent=2, ensure_ascii=False)

print(f"Successfully compiled all 50 T154 questions into scratch/t154_50_built_questions.json")
