import json

t156_perfect_data = [
  {
    "id": "134683",
    "title": "Q1: Define a quadratic function",
    "question_text": "Define a quadratic function and write its standard form f(x) = ax² + bx + c (where a ≠ 0).",
    "math_formula": "f(x) = ax^2 + bx + c, \\quad a \\neq 0",
    "optA": "f(x) = ax² + bx + c (a ≠ 0), graph is a parabola",
    "optB": "f(x) = mx + b, graph is a straight line",
    "optC": "f(x) = a^x, graph is an exponential curve",
    "optD": "f(x) = k/x, graph is a hyperbola",
    "correct_answer": "f(x) = ax² + bx + c (a ≠ 0), graph is a parabola",
    "show_image": 0,
    "image_url": None
  },
  {
    "id": "134684",
    "title": "Q2: Geometric effect of coefficient a",
    "question_text": "Explain the geometric effect of the leading coefficient a on the opening direction and width of the parabola.",
    "math_formula": "a > 0 \\implies \\bigcup, \\quad a < 0 \\implies \\bigcap",
    "optA": "If a > 0, opens upward (minimum); if a < 0, opens downward (maximum); larger |a| makes parabola narrower",
    "optB": "If a > 0, opens to the right; if a < 0, opens to the left",
    "optC": "The sign of a determines the y-intercept only",
    "optD": "If a > 0, the graph is a circle; if a < 0, the graph is a line",
    "correct_answer": "If a > 0, opens upward (minimum); if a < 0, opens downward (maximum); larger |a| makes parabola narrower",
    "show_image": 1,
    "image_url": "/images/g9_t156_q2.png"
  },
  {
    "id": "134685",
    "title": "Q3: Vertex form definition",
    "question_text": "Define the vertex form of a quadratic function f(x) = a(x - h)² + k and identify the vertex and axis of symmetry.",
    "math_formula": "f(x) = a(x - h)^2 + k",
    "optA": "Vertex is (h, k), axis of symmetry is x = h",
    "optB": "Vertex is (-h, -k), axis of symmetry is y = k",
    "optC": "Vertex is (a, b), axis of symmetry is x = 0",
    "optD": "Vertex is (k, h), axis of symmetry is y = h",
    "correct_answer": "Vertex is (h, k), axis of symmetry is x = h",
    "show_image": 0,
    "image_url": None
  },
  {
    "id": "134686",
    "title": "Q4: Convert standard form to vertex form",
    "question_text": "Convert the quadratic function f(x) = 2x² - 12x + 11 into vertex form by completing the square.",
    "math_formula": "f(x) = 2(x - 3)^2 - 7",
    "optA": "f(x) = 2(x - 3)² - 7, Vertex: (3, -7)",
    "optB": "f(x) = 2(x + 3)² + 7, Vertex: (-3, 7)",
    "optC": "f(x) = 2(x - 6)² - 25, Vertex: (6, -25)",
    "optD": "f(x) = (x - 3)² - 7, Vertex: (3, -7)",
    "correct_answer": "f(x) = 2(x - 3)² - 7, Vertex: (3, -7)",
    "show_image": 0,
    "image_url": None
  },
  {
    "id": "134687",
    "title": "Q5: Axis of symmetry formula",
    "question_text": "Find the axis of symmetry of the function f(x) = -3x² + 12x - 5 using h = -b / (2a).",
    "math_formula": "h = \\frac{-b}{2a} = \\frac{-12}{2(-3)} = 2",
    "optA": "Axis of symmetry: x = 2",
    "optB": "Axis of symmetry: x = -2",
    "optC": "Axis of symmetry: x = 4",
    "optD": "Axis of symmetry: y = 7",
    "correct_answer": "Axis of symmetry: x = 2",
    "show_image": 0,
    "image_url": None
  },
  {
    "id": "134688",
    "title": "Q6: Key features of quadratic function",
    "question_text": "Find the vertex, axis of symmetry, y-intercept, and x-intercepts of f(x) = x² - 6x + 8.",
    "math_formula": "f(x) = (x - 3)^2 - 1 = (x - 2)(x - 4)",
    "optA": "Vertex: (3, -1), Axis: x = 3, y-int: (0, 8), x-ints: (2, 0) and (4, 0)",
    "optB": "Vertex: (-3, 1), Axis: x = -3, y-int: (0, -8), x-ints: (-2, 0) and (-4, 0)",
    "optC": "Vertex: (6, 8), Axis: x = 6, y-int: (0, 3), x-ints: (1, 0) and (8, 0)",
    "optD": "Vertex: (0, 8), Axis: x = 0, y-int: (3, -1), x-ints: (0, 2) and (0, 4)",
    "correct_answer": "Vertex: (3, -1), Axis: x = 3, y-int: (0, 8), x-ints: (2, 0) and (4, 0)",
    "show_image": 1,
    "image_url": "/images/g9_t156_q6.png"
  },
  {
    "id": "134689",
    "title": "Q7: Maximum value of quadratic function",
    "question_text": "Determine the maximum value of the function f(x) = -2x² + 8x + 3 and state the x-value at which it occurs.",
    "math_formula": "h = \\frac{-8}{2(-2)} = 2, \\quad k = f(2) = 11",
    "optA": "Maximum value is 11 at x = 2",
    "optB": "Minimum value is -11 at x = -2",
    "optC": "Maximum value is 19 at x = 4",
    "optD": "Minimum value is 3 at x = 0",
    "correct_answer": "Maximum value is 11 at x = 2",
    "show_image": 1,
    "image_url": "/images/g9_t156_q7.png"
  },
  {
    "id": "134690",
    "title": "Q8: Domain and range opening upward",
    "question_text": "Find the domain and range of the function f(x) = (x + 4)² - 5.",
    "math_formula": "f(x) = (x + 4)^2 - 5",
    "optA": "Domain: (-∞, ∞), Range: [-5, ∞)",
    "optB": "Domain: [-4, ∞), Range: (-∞, ∞)",
    "optC": "Domain: (-∞, ∞), Range: (-∞, -5]",
    "optD": "Domain: [-5, ∞), Range: [-4, ∞)",
    "correct_answer": "Domain: (-∞, ∞), Range: [-5, ∞)",
    "show_image": 0,
    "image_url": None
  },
  {
    "id": "134691",
    "title": "Q9: Domain and range opening downward",
    "question_text": "Find the domain and range of the function f(x) = -(x - 1)² + 9.",
    "math_formula": "f(x) = -(x - 1)^2 + 9",
    "optA": "Domain: (-∞, ∞), Range: (-∞, 9]",
    "optB": "Domain: (-∞, ∞), Range: [9, ∞)",
    "optC": "Domain: [1, ∞), Range: (-∞, 9]",
    "optD": "Domain: (-∞, 9], Range: (-∞, ∞)",
    "correct_answer": "Domain: (-∞, ∞), Range: (-∞, 9]",
    "show_image": 0,
    "image_url": None
  },
  {
    "id": "134692",
    "title": "Q10: Projectile maximum height",
    "question_text": "A projectile's height is given by h(t) = -16t² + 64t + 80 (in feet). Find the maximum height and the time it takes to reach it.",
    "math_formula": "t = \\frac{-64}{2(-16)} = 2, \\quad h(2) = 144",
    "optA": "Maximum height of 144 feet after 2 seconds",
    "optB": "Maximum height of 80 feet after 4 seconds",
    "optC": "Maximum height of 128 feet after 1.5 seconds",
    "optD": "Maximum height of 160 feet after 3 seconds",
    "correct_answer": "Maximum height of 144 feet after 2 seconds",
    "show_image": 1,
    "image_url": "/images/g9_t156_q10.png"
  },
  {
    "id": "134693",
    "title": "Q11: Projectile ground impact time",
    "question_text": "Using h(t) = -16t² + 64t + 80, find the time t when the projectile hits the ground (h(t) = 0).",
    "math_formula": "-16(t^2 - 4t - 5) = 0 \\implies t = 5",
    "optA": "t = 5 seconds",
    "optB": "t = 4 seconds",
    "optC": "t = 8 seconds",
    "optD": "t = 2.5 seconds",
    "correct_answer": "t = 5 seconds",
    "show_image": 0,
    "image_url": None
  },
  {
    "id": "134694",
    "title": "Q12: x-intercepts of quadratic function",
    "question_text": "Find the x-intercepts of the function f(x) = x² - 5x - 14.",
    "math_formula": "(x - 7)(x + 2) = 0 \\implies x = 7, x = -2",
    "optA": "(7, 0) and (-2, 0)",
    "optB": "(-7, 0) and (2, 0)",
    "optC": "(14, 0) and (-1, 0)",
    "optD": "(5, 0) and (-14, 0)",
    "correct_answer": "(7, 0) and (-2, 0)",
    "show_image": 1,
    "image_url": "/images/g9_t156_q12.png"
  },
  {
    "id": "134695",
    "title": "Q13: Vertex and axis of f(x) = 3x² - 18x + 20",
    "question_text": "Find the vertex and axis of symmetry of f(x) = 3x² - 18x + 20 using h = -b / (2a).",
    "math_formula": "h = \\frac{18}{2(3)} = 3, \\quad k = f(3) = -7",
    "optA": "Vertex: (3, -7), Axis of symmetry: x = 3",
    "optB": "Vertex: (-3, 7), Axis of symmetry: x = -3",
    "optC": "Vertex: (3, 20), Axis of symmetry: x = 3",
    "optD": "Vertex: (6, -16), Axis of symmetry: x = 6",
    "correct_answer": "Vertex: (3, -7), Axis of symmetry: x = 3",
    "show_image": 1,
    "image_url": "/images/g9_t156_q13.png"
  },
  {
    "id": "134696",
    "title": "Q14: Transformations of y = (x - 3)² + 2",
    "question_text": "Describe the transformations required to obtain the graph of y = (x - 3)² + 2 from the parent function y = x².",
    "math_formula": "y = (x - 3)^2 + 2",
    "optA": "Shifted right 3 units and up 2 units",
    "optB": "Shifted left 3 units and down 2 units",
    "optC": "Shifted right 2 units and up 3 units",
    "optD": "Shifted left 3 units and up 2 units",
    "correct_answer": "Shifted right 3 units and up 2 units",
    "show_image": 1,
    "image_url": "/images/g9_t156_q14.png"
  },
  {
    "id": "134697",
    "title": "Q15: Reflection and stretch of y = -2x²",
    "question_text": "Describe the reflection and vertical stretch of y = -2x² compared to y = x².",
    "math_formula": "y = -2x^2",
    "optA": "Reflected over x-axis and vertically stretched by a factor of 2",
    "optB": "Reflected over y-axis and vertically compressed by a factor of 0.5",
    "optC": "Shifted down 2 units with no reflection",
    "optD": "Shifted left 2 units and reflected over y-axis",
    "correct_answer": "Reflected over x-axis and vertically stretched by a factor of 2",
    "show_image": 1,
    "image_url": "/images/g9_t156_q15.png"
  },
  {
    "id": "134698",
    "title": "Q16: Find quadratic function given vertex and point",
    "question_text": "Find the quadratic function in vertex form with vertex (2, 5) that passes through the point (4, 13).",
    "math_formula": "f(x) = a(x - 2)^2 + 5, \\quad 13 = a(4 - 2)^2 + 5 \\implies a = 2",
    "optA": "f(x) = 2(x - 2)² + 5",
    "optB": "f(x) = 3(x + 2)² - 5",
    "optC": "f(x) = (x - 2)² + 13",
    "optD": "f(x) = 4(x - 5)² + 2",
    "correct_answer": "f(x) = 2(x - 2)² + 5",
    "show_image": 0,
    "image_url": None
  },
  {
    "id": "134699",
    "title": "Q17: Discriminant and x-intercepts count",
    "question_text": "Calculate the discriminant b² - 4ac for f(x) = 2x² - 4x + 5 and state the number of x-intercepts.",
    "math_formula": "b^2 - 4ac = (-4)^2 - 4(2)(5) = 16 - 40 = -24",
    "optA": "Discriminant = -24, 0 x-intercepts",
    "optB": "Discriminant = 56, 2 x-intercepts",
    "optC": "Discriminant = 0, 1 x-intercept",
    "optD": "Discriminant = -8, 2 x-intercepts",
    "correct_answer": "Discriminant = -24, 0 x-intercepts",
    "show_image": 0,
    "image_url": None
  },
  {
    "id": "134700",
    "title": "Q18: Graph features of f(x) = -x² + 4x + 5",
    "question_text": "Graph the function f(x) = -x² + 4x + 5, and state its vertex, y-intercept, and x-intercepts.",
    "math_formula": "f(x) = -(x - 2)^2 + 9",
    "optA": "Vertex: (2, 9), y-int: (0, 5), x-ints: (-1, 0) and (5, 0)",
    "optB": "Vertex: (-2, 5), y-int: (0, 9), x-ints: (1, 0) and (-5, 0)",
    "optC": "Vertex: (4, 5), y-int: (0, -5), x-ints: (2, 0) and (9, 0)",
    "optD": "Vertex: (0, 5), y-int: (2, 9), x-ints: (0, -1) and (0, 5)",
    "correct_answer": "Vertex: (2, 9), y-int: (0, 5), x-ints: (-1, 0) and (5, 0)",
    "show_image": 1,
    "image_url": "/images/g9_t156_q18.png"
  },
  {
    "id": "134701",
    "title": "Q19: Business maximum revenue",
    "question_text": "A business models total daily revenue by R(x) = -5x² + 100x (in pesos). Find the price setting x that maximizes revenue and state the maximum revenue.",
    "math_formula": "x = \\frac{-100}{2(-5)} = 10, \\quad R(10) = 500",
    "optA": "Maximum revenue of ₱500 at x = 10",
    "optB": "Maximum revenue of ₱1,000 at x = 20",
    "optC": "Maximum revenue of ₱250 at x = 5",
    "optD": "Maximum revenue of ₱750 at x = 15",
    "correct_answer": "Maximum revenue of ₱500 at x = 10",
    "show_image": 1,
    "image_url": "/images/g9_t156_q19.png"
  },
  {
    "id": "134702",
    "title": "Q20: Maximize product of two numbers",
    "question_text": "Find two real numbers whose sum is 12 such that their product is maximized.",
    "math_formula": "P(x) = x(12 - x) = -x^2 + 12x \\implies x = 6",
    "optA": "Numbers are 6 and 6, maximum product = 36",
    "optB": "Numbers are 5 and 7, maximum product = 35",
    "optC": "Numbers are 4 and 8, maximum product = 32",
    "optD": "Numbers are 10 and 2, maximum product = 20",
    "correct_answer": "Numbers are 6 and 6, maximum product = 36",
    "show_image": 0,
    "image_url": None
  },
  {
    "id": "134703",
    "title": "Q21: Solve parameter k for minimum value",
    "question_text": "Find the value of k such that the minimum value of f(x) = x² - 6x + k is 4.",
    "math_formula": "k_{min} = 9 - 18 + k = 4 \\implies k = 13",
    "optA": "k = 13",
    "optB": "k = 5",
    "optC": "k = 9",
    "optD": "k = -5",
    "correct_answer": "k = 13",
    "show_image": 0,
    "image_url": None
  },
  {
    "id": "134704",
    "title": "Q22: Vertex form feature extraction",
    "question_text": "Given f(x) = -0.5(x + 3)² + 8, state the vertex, axis of symmetry, opening direction, and maximum/minimum value.",
    "math_formula": "f(x) = -0.5(x + 3)^2 + 8",
    "optA": "Vertex: (-3, 8), Axis: x = -3, Opens downward, Maximum = 8",
    "optB": "Vertex: (3, -8), Axis: x = 3, Opens upward, Minimum = -8",
    "optC": "Vertex: (3, 8), Axis: x = 3, Opens downward, Maximum = 8",
    "optD": "Vertex: (-3, -8), Axis: x = -3, Opens upward, Minimum = 8",
    "correct_answer": "Vertex: (-3, 8), Axis: x = -3, Opens downward, Maximum = 8",
    "show_image": 1,
    "image_url": "/images/g9_t156_q22.png"
  },
  {
    "id": "134705",
    "title": "Q23: Zeros of f(x) = 3x² - 12",
    "question_text": "Find the zeros of the function f(x) = 3x² - 12.",
    "math_formula": "3(x^2 - 4) = 0 \\implies x = 2, x = -2",
    "optA": "x = 2 and x = -2",
    "optB": "x = 4 and x = -4",
    "optC": "x = 12 and x = -12",
    "optD": "x = 3 and x = 0",
    "correct_answer": "x = 2 and x = -2",
    "show_image": 0,
    "image_url": None
  },
  {
    "id": "134706",
    "title": "Q24: Zeros of perfect square trinomial",
    "question_text": "Find the zeros of f(x) = x² + 4x + 4 and describe the graph's behavior at the x-intercept.",
    "math_formula": "(x + 2)^2 = 0 \\implies x = -2",
    "optA": "x = -2 (one double root, graph touches x-axis at (-2, 0))",
    "optB": "x = 2 and x = -2 (two distinct x-intercepts)",
    "optC": "x = 4 and x = 1",
    "optD": "No real zeros (graph remains above x-axis)",
    "correct_answer": "x = -2 (one double root, graph touches x-axis at (-2, 0))",
    "show_image": 1,
    "image_url": "/images/g9_t156_q24.png"
  },
  {
    "id": "134707",
    "title": "Q25: Factored form of f(x) = -x² + 4x + 12",
    "question_text": "Convert f(x) = -x² + 4x + 12 into factored form and identify its zeros.",
    "math_formula": "f(x) = -(x - 6)(x + 2)",
    "optA": "f(x) = -(x - 6)(x + 2); Zeros: x = 6 and x = -2",
    "optB": "f(x) = (x + 6)(x - 2); Zeros: x = -6 and x = 2",
    "optC": "f(x) = -(x - 4)(x - 3); Zeros: x = 4 and x = 3",
    "optD": "f(x) = (x - 12)(x + 1); Zeros: x = 12 and x = -1",
    "correct_answer": "f(x) = -(x - 6)(x + 2); Zeros: x = 6 and x = -2",
    "show_image": 0,
    "image_url": None
  },
  {
    "id": "134708",
    "title": "Q26: Range over restricted domain",
    "question_text": "Determine the range of f(x) = x² - 4x + 3 when restricted to the domain [0, 4].",
    "math_formula": "f(2) = -1, \\quad f(0) = 3, \\quad f(4) = 3 \\implies \\text{Range: } [-1, 3]",
    "optA": "Domain: [0, 4], Range: [-1, 3]",
    "optB": "Domain: [0, 4], Range: [0, 4]",
    "optC": "Domain: [0, 4], Range: [3, 15]",
    "optD": "Domain: [0, 4], Range: [-4, 3]",
    "correct_answer": "Domain: [0, 4], Range: [-1, 3]",
    "show_image": 1,
    "image_url": "/images/g9_t156_q26.png"
  },
  {
    "id": "134709",
    "title": "Q27: Parabola equation from vertex and y-intercept",
    "question_text": "Find the equation of the parabola with vertex (1, -4) and y-intercept (0, -3).",
    "math_formula": "f(x) = (x - 1)^2 - 4 = x^2 - 2x - 3",
    "optA": "f(x) = x² - 2x - 3",
    "optB": "f(x) = x² + 2x - 3",
    "optC": "f(x) = 2x² - 4x - 3",
    "optD": "f(x) = x² - x - 4",
    "correct_answer": "f(x) = x² - 2x - 3",
    "show_image": 0,
    "image_url": None
  },
  {
    "id": "134710",
    "title": "Q28: Parabola equation from x-intercepts and point",
    "question_text": "Find the equation of the parabola having x-intercepts (-1, 0) and (5, 0) and passing through (2, 9).",
    "math_formula": "f(x) = -(x + 1)(x - 5) = -x^2 + 4x + 5",
    "optA": "f(x) = -x² + 4x + 5",
    "optB": "f(x) = x² - 4x - 5",
    "optC": "f(x) = -2x² + 8x + 10",
    "optD": "f(x) = -x² - 4x + 5",
    "correct_answer": "f(x) = -x² + 4x + 5",
    "show_image": 0,
    "image_url": None
  },
  {
    "id": "134711",
    "title": "Q29: Arch bridge parabolic model",
    "question_text": "An arch bridge is modeled by h(x) = -0.05x² + 2x (in meters). Find the maximum height of the arch and the width of its base.",
    "math_formula": "x_{vertex} = 20 \\implies h_{max} = 20\\text{ m}, \\quad \\text{Width} = 40\\text{ m}",
    "optA": "Maximum height = 20 meters, Span width = 40 meters",
    "optB": "Maximum height = 40 meters, Span width = 20 meters",
    "optC": "Maximum height = 10 meters, Span width = 50 meters",
    "optD": "Maximum height = 25 meters, Span width = 30 meters",
    "correct_answer": "Maximum height = 20 meters, Span width = 40 meters",
    "show_image": 1,
    "image_url": "/images/g9_t156_q29.png"
  },
  {
    "id": "134712",
    "title": "Q30: Vertical stretch/compression comparison",
    "question_text": "Compare the graphs of y = x², y = 3x², and y = (1/3)x².",
    "math_formula": "y = 3x^2 \\text{ (narrower)}, \\quad y = \\frac{1}{3}x^2 \\text{ (wider)}",
    "optA": "y = 3x² is narrower than y = x², while y = (1/3)x² is wider than y = x²",
    "optB": "y = 3x² is wider than y = x², while y = (1/3)x² is narrower",
    "optC": "All three functions have different vertices",
    "optD": "y = 3x² opens downward while y = (1/3)x² opens upward",
    "correct_answer": "y = 3x² is narrower than y = x², while y = (1/3)x² is wider than y = x²",
    "show_image": 1,
    "image_url": "/images/g9_t156_q30.png"
  },
  {
    "id": "134713",
    "title": "Q31: Minimum of f(x) = x² + 10x + 30",
    "question_text": "Find the minimum value of f(x) = x² + 10x + 30.",
    "math_formula": "h = -5, \\quad k = 25 - 50 + 30 = 5",
    "optA": "Minimum value is 5 at x = -5",
    "optB": "Maximum value is 30 at x = 0",
    "optC": "Minimum value is -5 at x = 5",
    "optD": "Minimum value is 0 at x = -10",
    "correct_answer": "Minimum value is 5 at x = -5",
    "show_image": 0,
    "image_url": None
  },
  {
    "id": "134714",
    "title": "Q32: Maximum of f(x) = -3x² - 12x - 7",
    "question_text": "Find the maximum value of f(x) = -3x² - 12x - 7.",
    "math_formula": "h = -2, \\quad k = -12 + 24 - 7 = 5",
    "optA": "Maximum value is 5 at x = -2",
    "optB": "Minimum value is -7 at x = 0",
    "optC": "Maximum value is 12 at x = 2",
    "optD": "Minimum value is 5 at x = -2",
    "correct_answer": "Maximum value is 5 at x = -2",
    "show_image": 0,
    "image_url": None
  },
  {
    "id": "134715",
    "title": "Q33: Zeros of f(x) = x² - 8x + 15",
    "question_text": "Find the zeros of f(x) = x² - 8x + 15.",
    "math_formula": "(x - 3)(x - 5) = 0 \\implies x = 3, x = 5",
    "optA": "x = 3 and x = 5",
    "optB": "x = -3 and x = -5",
    "optC": "x = 15 and x = 1",
    "optD": "x = 8 and x = -15",
    "correct_answer": "x = 3 and x = 5",
    "show_image": 1,
    "image_url": "/images/g9_t156_q33.png"
  },
  {
    "id": "134716",
    "title": "Q34: Graph features of f(x) = 2(x - 1)² - 8",
    "question_text": "Graph the function f(x) = 2(x - 1)² - 8, and state its vertex, y-intercept, and x-intercepts.",
    "math_formula": "Vertex: (1, -8), \\quad y\\text{-int: } (0, -6), \\quad x\\text{-ints: } (3, 0), (-1, 0)",
    "optA": "Vertex: (1, -8), y-int: (0, -6), x-ints: (3, 0) and (-1, 0)",
    "optB": "Vertex: (-1, 8), y-int: (0, 6), x-ints: (-3, 0) and (1, 0)",
    "optC": "Vertex: (2, -8), y-int: (0, -8), x-ints: (4, 0) and (0, 0)",
    "optD": "Vertex: (1, 8), y-int: (0, -6), x-ints: (2, 0) and (-2, 0)",
    "correct_answer": "Vertex: (1, -8), y-int: (0, -6), x-ints: (3, 0) and (-1, 0)",
    "show_image": 1,
    "image_url": "/images/g9_t156_q34.png"
  },
  {
    "id": "134717",
    "title": "Q35: Horizontal shift comparison",
    "question_text": "Compare the horizontal shifts of f(x) = (x + 5)² and g(x) = (x - 3)².",
    "math_formula": "f(x) \\text{ shifted left 5, } g(x) \\text{ shifted right 3}",
    "optA": "f(x) vertex is at x = -5, g(x) vertex is at x = 3; 8 units apart",
    "optB": "f(x) vertex is at x = 5, g(x) vertex is at x = -3; 2 units apart",
    "optC": "Both functions have the same vertex at (0, 0)",
    "optD": "f(x) is shifted up 5 units, g(x) is shifted down 3 units",
    "correct_answer": "f(x) vertex is at x = -5, g(x) vertex is at x = 3; 8 units apart",
    "show_image": 1,
    "image_url": "/images/g9_t156_q35.png"
  },
  {
    "id": "134718",
    "title": "Q36: Vertical shift comparison",
    "question_text": "Compare the vertical shifts of f(x) = x² + 4 and g(x) = x² - 7.",
    "math_formula": "f(x) \\text{ shifted up 4, } g(x) \\text{ shifted down 7}",
    "optA": "f(x) shifted up 4 units, g(x) shifted down 7 units; 11 units apart vertically",
    "optB": "f(x) shifted right 4 units, g(x) shifted left 7 units",
    "optC": "Both functions have x-intercepts at (0, 0)",
    "optD": "f(x) opens downward while g(x) opens upward",
    "correct_answer": "f(x) shifted up 4 units, g(x) shifted down 7 units; 11 units apart vertically",
    "show_image": 1,
    "image_url": "/images/g9_t156_q36.png"
  },
  {
    "id": "134719",
    "title": "Q37: Complete the square for f(x) = 2x² + 8x + 3",
    "question_text": "Find the vertex of f(x) = 2x² + 8x + 3 by completing the square.",
    "math_formula": "f(x) = 2(x + 2)^2 - 5 \\implies \\text{Vertex: } (-2, -5)",
    "optA": "Vertex: (-2, -5)",
    "optB": "Vertex: (2, 5)",
    "optC": "Vertex: (-4, 3)",
    "optD": "Vertex: (4, -13)",
    "correct_answer": "Vertex: (-2, -5)",
    "show_image": 0,
    "image_url": None
  },
  {
    "id": "134720",
    "title": "Q38: Farmer rectangular pen optimization",
    "question_text": "A farmer uses 40 meters of fencing to enclose a rectangular pen against a barn wall. Find the dimensions and maximum area.",
    "math_formula": "A(x) = x(40 - 2x) = -2x^2 + 40x \\implies \\text{Max at } x = 10, A = 200\\text{ m}^2",
    "optA": "Width = 10 m, Length = 20 m, Maximum Area = 200 m²",
    "optB": "Width = 15 m, Length = 10 m, Maximum Area = 150 m²",
    "optC": "Width = 20 m, Length = 20 m, Maximum Area = 400 m²",
    "optD": "Width = 8 m, Length = 24 m, Maximum Area = 192 m²",
    "correct_answer": "Width = 10 m, Length = 20 m, Maximum Area = 200 m²",
    "show_image": 1,
    "image_url": "/images/g9_t156_q38.png"
  },
  {
    "id": "134721",
    "title": "Q39: Range of f(x) = -3(x - 4)² + 15",
    "question_text": "State the range of the function f(x) = -3(x - 4)² + 15.",
    "math_formula": "\\text{Vertex: } (4, 15), \\quad a < 0 \\implies \\text{Range: } (-\\infty, 15]",
    "optA": "Range: (-∞, 15]",
    "optB": "Range: [15, ∞)",
    "optC": "Range: (-∞, 4]",
    "optD": "Range: [-3, ∞)",
    "correct_answer": "Range: (-∞, 15]",
    "show_image": 0,
    "image_url": None
  },
  {
    "id": "134722",
    "title": "Q40: Quadratic function passing through three points",
    "question_text": "Find the quadratic function whose graph passes through the three points (0, 3), (1, 6), and (2, 11).",
    "math_formula": "f(x) = x^2 + 2x + 3",
    "optA": "f(x) = x² + 2x + 3",
    "optB": "f(x) = 2x² + x + 3",
    "optC": "f(x) = x² + 3x + 2",
    "optD": "f(x) = 3x² - x + 3",
    "correct_answer": "f(x) = x² + 2x + 3",
    "show_image": 0,
    "image_url": None
  },
  {
    "id": "134723",
    "title": "Q41: Find k such that vertex lies on x-axis",
    "question_text": "Find the value of k such that the vertex of f(x) = x² - 8x + k lies on the x-axis.",
    "math_formula": "k_{vertex} = 16 - 32 + k = 0 \\implies k = 16",
    "optA": "k = 16",
    "optB": "k = 8",
    "optC": "k = 64",
    "optD": "k = -16",
    "correct_answer": "k = 16",
    "show_image": 0,
    "image_url": None
  },
  {
    "id": "134724",
    "title": "Q42: Find c such that maximum value is 25",
    "question_text": "Find the value of c such that the maximum value of f(x) = -2x² + 12x + c is 25.",
    "math_formula": "h = 3, \\quad -18 + 36 + c = 25 \\implies c = 7",
    "optA": "c = 7",
    "optB": "c = 25",
    "optC": "c = 13",
    "optD": "c = -7",
    "correct_answer": "c = 7",
    "show_image": 0,
    "image_url": None
  },
  {
    "id": "134725",
    "title": "Q43: Photo border area function",
    "question_text": "A rectangular photograph is 8 cm by 10 cm. A uniform border of width x is added around it. Write the total area function A(x) in standard quadratic form.",
    "math_formula": "A(x) = (8 + 2x)(10 + 2x) = 4x^2 + 36x + 80",
    "optA": "A(x) = 4x² + 36x + 80",
    "optB": "A(x) = x² + 18x + 80",
    "optC": "A(x) = 2x² + 18x + 80",
    "optD": "A(x) = 4x² + 18x + 40",
    "correct_answer": "A(x) = 4x² + 36x + 80",
    "show_image": 0,
    "image_url": None
  },
  {
    "id": "134726",
    "title": "Q44: Symmetry property of parabolas",
    "question_text": "Explain the symmetry property of parabolas: if f(2) = 7 and f(8) = 7, what is the x-coordinate of the vertex?",
    "math_formula": "h = \\frac{2 + 8}{2} = 5 \\implies x = 5",
    "optA": "x = 5",
    "optB": "x = 7",
    "optC": "x = 10",
    "optD": "x = 3",
    "correct_answer": "x = 5",
    "show_image": 0,
    "image_url": None
  },
  {
    "id": "134727",
    "title": "Q45: Zeros of 4x² - 12x + 9",
    "question_text": "Find the zeros of f(x) = 4x² - 12x + 9 algebraically and describe the graph's relationship with the x-axis.",
    "math_formula": "(2x - 3)^2 = 0 \\implies x = 1.5",
    "optA": "x = 1.5 (one double root, graph touches x-axis at (1.5, 0))",
    "optB": "x = 3 and x = -3",
    "optC": "x = 4 and x = 9",
    "optD": "No real zeros",
    "correct_answer": "x = 1.5 (one double root, graph touches x-axis at (1.5, 0))",
    "show_image": 0,
    "image_url": None
  },
  {
    "id": "134728",
    "title": "Q46: Domain, range, zeros of f(x) = -(x - 5)²",
    "question_text": "Find the domain, range, and zeros of f(x) = -(x - 5)².",
    "math_formula": "\\text{Vertex: } (5, 0), \\quad a < 0",
    "optA": "Domain: (-∞, ∞), Range: (-∞, 0], Zero: x = 5",
    "optB": "Domain: [5, ∞), Range: [0, ∞), Zero: x = -5",
    "optC": "Domain: (-∞, ∞), Range: [0, ∞), Zeros: x = ±5",
    "optD": "Domain: (-∞, 0], Range: (-∞, ∞), Zero: x = 0",
    "correct_answer": "Domain: (-∞, ∞), Range: (-∞, 0], Zero: x = 5",
    "show_image": 1,
    "image_url": "/images/g9_t156_q46.png"
  },
  {
    "id": "134729",
    "title": "Q47: Effect of parameter c on vertical position",
    "question_text": "Analyze the effect of changing parameter c in f(x) = ax² + bx + c on the vertical position of the graph.",
    "math_formula": "y\\text{-intercept is } (0, c)",
    "optA": "c is the y-intercept; increasing c shifts the graph vertically upward, decreasing c shifts it downward",
    "optB": "c determines the width of the parabola",
    "optC": "c shifts the graph horizontally left or right",
    "optD": "c flips the opening direction of the parabola",
    "correct_answer": "c is the y-intercept; increasing c shifts the graph vertically upward, decreasing c shifts it downward",
    "show_image": 0,
    "image_url": None
  },
  {
    "id": "134730",
    "title": "Q48: Effect of parameter h on horizontal position",
    "question_text": "Analyze the effect of changing parameter h in f(x) = a(x - h)² + k on the horizontal position of the graph.",
    "math_formula": "\\text{Horizontal shift by } h \\text{ units}",
    "optA": "Increasing h shifts the parabola to the right; decreasing h shifts it to the left",
    "optB": "Increasing h shifts the parabola upward; decreasing h shifts it downward",
    "optC": "Increasing h makes the parabola wider; decreasing h makes it narrower",
    "optD": "Parameter h has no effect on the graph's position",
    "correct_answer": "Increasing h shifts the parabola to the right; decreasing h shifts it to the left",
    "show_image": 0,
    "image_url": None
  },
  {
    "id": "134731",
    "title": "Q49: Rooftop ball physical domain and range",
    "question_text": "A ball is thrown from a rooftop 30 m high with an initial velocity of 25 m/s. Its height is h(t) = -5t² + 25t + 30. Graph the function and state the domain and range appropriate for this physical context.",
    "math_formula": "h(t) = -5t^2 + 25t + 30 = -5(t - 6)(t + 1)",
    "optA": "Domain: [0, 6] seconds, Range: [0, 61.25] meters",
    "optB": "Domain: (-∞, ∞), Range: (-∞, ∞)",
    "optC": "Domain: [0, 30] seconds, Range: [0, 25] meters",
    "optD": "Domain: [0, 5] seconds, Range: [30, 60] meters",
    "correct_answer": "Domain: [0, 6] seconds, Range: [0, 61.25] meters",
    "show_image": 1,
    "image_url": "/images/g9_t156_q49.png"
  },
  {
    "id": "134732",
    "title": "Q50: Maximize product with given sum",
    "question_text": "State the quadratic function that represents the product of two numbers whose sum is 20, and find the maximum product.",
    "math_formula": "P(x) = x(20 - x) = -x^2 + 20x \\implies \\text{Max at } x = 10, P = 100",
    "optA": "P(x) = -x² + 20x; Maximum product = 100 at x = 10",
    "optB": "P(x) = x² - 20x; Maximum product = 200 at x = 20",
    "optC": "P(x) = -2x² + 20x; Maximum product = 50 at x = 5",
    "optD": "P(x) = -x² + 10x; Maximum product = 25 at x = 5",
    "correct_answer": "P(x) = -x² + 20x; Maximum product = 100 at x = 10",
    "show_image": 0,
    "image_url": None
  }
]

with open('scratch/t156_50_perfect_built.json', 'w', encoding='utf-8') as f:
    json.dump(t156_perfect_data, f, indent=2, ensure_ascii=False)

print(f"Successfully compiled all 50 T156 questions into scratch/t156_50_perfect_built.json")
